name: ðŸ·ï¸ Auto tag and delete release branch

on:
  workflow_dispatch:
    inputs:
      retain_limit:
        description: "Count of valid branches to retain"
        type: number
        default: 4

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    outputs:
      all_branches: ${{ steps.get_release_branch.outputs.all_branches }}
      valid_branches: ${{ steps.get_release_branch.outputs.valid_branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Release Branches
        id: get_release_branch
        run: |
          # Fetch all branches
          git fetch --all

          # Get all release branches from latest to oldest
          ALL_BRANCHES=$(git branch -r --sort=-committerdate | grep 'origin/release/' | sed 's|origin/||')
          echo "All Branches $ALL_BRANCHES"

          # Get the latest release branch with pattern release/[number].[number].[number]
          VALID_BRANCHES=$(echo "$ALL_BRANCHES" | grep -E 'release/[0-9]+\.[0-9]+\.[0-9]+$')
          echo "Valid Branches $VALID_BRANCHES"

          # Set output
          ALL_BRANCHES=$(echo "$ALL_BRANCHES" | tr '\n' ' ' | sed 's/^ *//;s/ *$//')
          echo "all_branches=$ALL_BRANCHES" >> $GITHUB_OUTPUT
          VALID_BRANCHES=$(echo "$VALID_BRANCHES" | tr '\n' ' ' | sed 's/^ *//;s/ *$//')
          echo "valid_branches=$VALID_BRANCHES" >> $GITHUB_OUTPUT

  autotag-old-branch:
    name: Auto tag old release branch
    runs-on: ubuntu-latest
    needs: get-release-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag
        uses: actions/github-script@v7
        env:
          RELEASE_BRANCHES: ${{ needs.get-release-branch.outputs.valid_branches }}
          RETAINED_BRANCH_COUNT: ${{ inputs.retain_limit }}
        with:
          script: |
            const { RELEASE_BRANCHES, RETAINED_BRANCH_COUNT } = process.env;
            const releaseBranches = RELEASE_BRANCHES.split('   ');
            console.log('Release Branches:', releaseBranches);

            for (let i = releaseBranches.length - 1; i >= releaseBranches.length - RETAINED_BRANCH_COUNT; i--) {
              const oldBranch = releaseBranches[i];

              // Create a tag for the old branch
              const oldTag = `v${oldBranch.replace('release/', '')}`;
              try {
                // Try to get the tag
                await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${oldTag}`
                })

                console.log(`Tag ${oldTag} already exists.`);
              } catch (error) {
                // If the tag does not exist, create it
                if (error.status === 404) {
                  console.log(`Creating tag ${oldTag}`);

                  const branch = await github.rest.repos.getBranch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    branch: oldBranch
                  })

                  await github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `refs/tags/${oldTag}`,
                    sha: branch.data.commit.sha
                  });
                  console.log(`Tag ${oldTag} created successfully.`);
                } else {
                  throw error;
                }
              }
            }

  get-retained-branch-count:
    name: Get Retained Branch Count
    needs: [get-release-branch, autotag-old-branch]
    runs-on: ubuntu-latest
    outputs:
      retained_branch_count: ${{ steps.get_count.outputs.retained_branch_count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Retained Branch Count
        id: get_count
        uses: actions/github-script@v7
        env:
          ALL_BRANCHES: ${{ needs.get-release-branch.outputs.all_branches }}
        with:
          script: |
            const { ALL_BRANCHES } = process.env;
            const allBranches = ALL_BRANCHES.split('   ');
            console.log('All branches:', allBranches);

            const validPattern = /^release\/\d+\.\d+\.\d+$/;
            const retainLimit = parseInt('${{ inputs.retain_limit }}');

            // Find positions of valid branches
            const validBranches = [];
            let lastValidIndex = -1;

            let i = 0;
            while (validBranches.length < retainLimit && i < allBranches.length) {
              const branch = allBranches[i].trim();
              if (validPattern.test(branch)) {
                validBranches.push(branch);
                lastValidIndex = i;
              }
              i++;
            }

            if (lastValidIndex === -1) {
              console.log('No valid release branches found.');
              return;
            }

            console.log(`Total branches to retain: ${lastValidIndex + 1}`);
            core.setOutput('retained_branch_count', lastValidIndex + 1);

  cleanup-release-branch:
    name: Cleanup Old Release Branches
    needs: get-retained-branch-count
    uses: ./.github/workflows/test-echo.yml
    with:
      BRANCH_LIMIT: ${{ needs.get-retained-branch-count.outputs.retained_branch_count }}
