name: ðŸ·ï¸ Auto tag and delete release branch

on:
  workflow_call:
    inputs:
      retained_branch_count:
        description: "Count of branches to retain"
        type: number
        default: 5
  workflow_dispatch:
    inputs:
      retained_branch_count:
        description: "Count of branches to retain"
        type: number
        default: 5

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    outputs:
      release_branches: ${{ steps.get_all_release_branch.outputs.release_branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get All Release Branches
        id: get_all_release_branch
        run: |
          # Fetch all branches
          git fetch --all

          # Get all release branches
          RELEASE_BRANCHES=$(git branch -r --sort=committerdate | grep 'origin/release/' | sed 's|origin/||')
          echo "Branches $RELEASE_BRANCHES"
          RELEASE_BRANCHES=$(echo "$RELEASE_BRANCHES" | tr '\n' ' ' | sed 's/^ *//;s/ *$//')
          echo "release_branches=$RELEASE_BRANCHES" >> $GITHUB_OUTPUT
  autotag-old-valid-branch:
    runs-on: ubuntu-latest
    needs: get-release-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag for old valid release branches
        uses: actions/github-script@v7
        env:
          RELEASE_BRANCHES: ${{ needs.get-release-branch.outputs.release_branches }}
          RETAINED_BRANCH_COUNT: ${{ inputs.retained_branch_count }}
        with:
          script: |
            const { RELEASE_BRANCHES, RETAINED_BRANCH_COUNT } = process.env;
            const allBranches = RELEASE_BRANCHES.split('   ');
            console.log('All Release Branches', allBranches);

            // Exclude the last RETAINED_BRANCH_COUNT branches
            const oldBranches = allBranches.slice(0, allBranches.length - RETAINED_BRANCH_COUNT);
            console.log(`Old branches (excluding last ${RETAINED_BRANCH_COUNT})`, oldBranches);

            // Then filter to only include those matching semantic version format (release/x.y.z)
            const pattern = /^release\/\d+\.\d+\.\d+$/;
            const validBranches = oldBranches.filter(branch => pattern.test(branch.trim()));
            console.log('Valid release branches', validBranches);

            // Create tag for filtered release branches
            console.log(`Creating tags for ${validBranches.length} release branches \n\n`);
            for (let i = 0; i < validBranches.length; i++) {
              const oldBranch = validBranches[i];

              // Create a tag for the old branch
              const oldTag = `v${oldBranch.replace('release/', '')}`;
              try {
                // Try to get the tag
                await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${oldTag}`
                })

                console.log(`Tag ${oldTag} already exists.`);
              } catch (error) {
                // If the tag does not exist, create it
                if (error.status === 404) {
                  console.log(`Creating tag ${oldTag}`);

                  const branch = await github.rest.repos.getBranch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    branch: oldBranch
                  })

                  await github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `refs/tags/${oldTag}`,
                    sha: branch.data.commit.sha
                  });
                  console.log(`Tag ${oldTag} created successfully.`);
                } else {
                  throw error;
                }
              }
            }
  cleanup-release-branch:
    runs-on: ubuntu-latest
    needs: autotag-old-valid-branch
    name: Dummy cleanup job
    steps:
      - name: Dummy step
        run: echo "This is a placeholder for the actual cleanup job that would delete old release"
