name: ðŸ·ï¸ Auto tag and delete release branch

on:
  workflow_dispatch:
    inputs:
      retain_limit:
        description: 'Count of valid branches to retain'
        type: number
        default: 4

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    outputs:
      all_branches: ${{ steps.get_all_release_branch.outputs.release_branches }}
      valid_branches: ${{ steps.get_valid_release_branch.outputs.release_branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get All Release Branches
        id: get_all_release_branch
        run: |
          # Fetch all branches
          git fetch --all

          # Get all release branches from latest to oldest
          RELEASE_BRANCHES=$(git branch -r --sort=-committerdate | grep 'origin/release/' | sed 's|origin/||')
          echo "Branches $RELEASE_BRANCHES"
          RELEASE_BRANCHES=$(echo "$RELEASE_BRANCHES" | tr '\n' ' ' | sed 's/^ *//;s/ *$//')
          echo "all_branches=$RELEASE_BRANCHES" >> $GITHUB_OUTPUT
      - name: Get Valid Release Branches
        id: get_valid_release_branch
        run: |
          # Fetch all branches
          git fetch --all

          # Get the latest release branch with pattern release/[number].[number].[number]
          RELEASE_BRANCHES=$(git branch -r --sort=-committerdate | grep -E 'origin/release/[0-9]+\.[0-9]+\.[0-9]+$' | sed 's|origin/||' | sort -V)
          echo "Branches $RELEASE_BRANCHES"
          RELEASE_BRANCHES=$(echo "$RELEASE_BRANCHES" | tr '\n' ' ' | sed 's/^ *//;s/ *$//')
          echo "valid_branches=$RELEASE_BRANCHES" >> $GITHUB_OUTPUT

  autotag-old-branch:
    name: Auto tag old release branch
    runs-on: ubuntu-latest
    needs: get-release-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - name: Create tag and delete branch
        uses: actions/github-script@v7
        env:
          RELEASE_BRANCHES: ${{ needs.get-release-branch.outputs.valid_branches }}
          RETAINED_BRANCH_COUNT: ${{ inputs.retain_limit }}
        with:
          script: |
            const { RELEASE_BRANCHES, RETAINED_BRANCH_COUNT } = process.env;
            const releaseBranches = RELEASE_BRANCHES.split('   ');
            console.log('release Branch', releaseBranches);

            // Delete all release branches except the last {{ RETAINED_BRANCH_COUNT }}
            console.log(`Delete all release branches except the last ${RETAINED_BRANCH_COUNT} \n\n`);
            for (let i = 0; i < releaseBranches.length - RETAINED_BRANCH_COUNT; i++) {
              const oldBranch = releaseBranches[i];

              // Create a tag for the old branch
              const oldTag = `v${oldBranch.replace('release/', '')}`;
              try {
                // Try to get the tag
                await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${oldTag}`
                })

                console.log(`Tag ${oldTag} already exists.`);
              } catch (error) {
                // If the tag does not exist, create it
                if (error.status === 404) {
                  console.log(`Creating tag ${oldTag}`);

                  const branch = await github.rest.repos.getBranch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    branch: oldBranch
                  })

                  await github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `refs/tags/${oldTag}`,
                    sha: branch.data.commit.sha
                  });
                  console.log(`Tag ${oldTag} created successfully.`);
                } else {
                  throw error;
                }
              }
            }

  get-retained-branch-count:
    name: Get Retained Branch Count
    needs: autotag-old-branch
    runs-on: ubuntu-latest
    outputs:
      retained_branch_count: ${{ steps.get_count.outputs.retained_branch_count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Retained Branch Count
        id: get_count
        uses: actions/github-script@v7
        env:
          ALL_BRANCHES: ${{ needs.get-release-branch.outputs.all_branches }}
        with:
          script: |
            const { ALL_BRANCHES } = process.env;
            const allBranches = ALL_BRANCHES.split('   ');
            console.log('All branches:', allBranches);

            const validPattern = /^release\/\d+\.\d+\.\d+$/;
            const retainLimit = parseInt('${{ inputs.retain_limit }}');

            // Find positions of valid branches
            const validBranches = [];
            let lastValidIndex = -1;

            allBranches.forEach((branch, index) => {
              const branchName = branch.trim();
              if (validPattern.test(branchName)) {
                validBranches.push(branchName);
                lastValidIndex = index;
              }

              if (validBranches.length === retainLimit) {
                return;
              }
            });

            if (lastValidIndex === -1) {
              console.log('No valid release branches found.');
              return;
            }

            console.log(`Total branches to retain: ${lastValidIndex + 1}`);
            core.setOutput('retained_branch_count', lastValidIndex + 1);

  cleanup-release-branch:
    name: Cleanup Old Release Branches
    needs: get-retained-branch-count
    runs-on: ubuntu-latest
    steps:
      - name: Echo retained branch count
        run: echo "Retained branch count: ${{ needs.get-retained-branch-count.outputs.retained_branch_count }}"
