name: Request to Publish

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    name: Create Pull Request to publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make changes
        run: |
          # Make any necessary changes to trigger the publish process
          echo "Triggering publish process by making a dummy change." > dummy.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR"
          commit-message: "Update"
          branch: 'publish-rc'