name: Remove refs

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix of refs to remove (e.g., 'release/')"
        required: true
        default: "release/"

jobs:
  remove-refs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove refs with specified prefix
        id: get-branches
        env:
          PREFIX: ${{ github.event.inputs.prefix }}
        run: |
          echo "Removing refs with prefix: $PREFIX"
          git fetch --all
          refs_to_remove=$(git branch -r | grep "origin/$PREFIX" | sed 's|origin/||')

          if [ -z "$refs_to_remove" ]; then
            echo "No refs found with prefix '$PREFIX'."
            exit 0
          fi

          echo "Refs to remove:"
          echo "$refs_to_remove"

          // set to output for next step
          echo "refs_to_remove=$(echo "$refs_to_remove" | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Delete Branch
        uses: actions/github-script@v7
        env:
          REFS_TO_REMOVE: ${{ steps.get-branches.outputs.refs_to_remove }}
        with:
          script: |
            const branchToDelete = process.env.REFS_TO_REMOVE;
            if (branchToDelete != 'develop' && !branchToDelete.startsWith('test/')) {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchToDelete}`
              });
              console.log('Delete branch', branchToDelete);
            } else {
              core.setFailed('Refusing to delete branch: ' + branchToDelete);
            }
