name: 'Test Steps Sequence Workflow'

on:
  push:
    branches:
      - chore/test-delete

jobs:
  test_steps_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute Test Steps Action
        uses: ./.github/actions/test-steps