name: "Call Simple Workflow"
env:
  BRANCH: "cd-test"

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    uses: ./.github/workflows/autotag-release.yml
