name: Test Echo Tuesday

# https://superuser.com/questions/428807/run-a-cron-job-on-the-first-monday-of-every-month // old implementation
on:
  workflow_call:
    inputs:
      retained_branch_count:
        description: "Count of branches to retain"
        type: number
        default: 7

jobs:
  echo_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          RETAINED_BRANCH_COUNT: ${{ inputs.retained_branch_count }}
        with:
          script: |
            const { RETAINED_BRANCH_COUNT } = process.env;
            console.log(`Retained branch count: ${RETAINED_BRANCH_COUNT}`);