name: "Call Simple Workflow"

on:
  workflow_dispatch:

jobs:
  checkout_some_branch:
    uses: actions/checkout@v4
    with:
      ref: refs/heads/cd-test
      
  call_simple_workflow:
    uses: ./.github/workflows/simple.yml
    with:
      checkout_branch: ${{ github.ref }}
