name: test trigger on push

on:
  push:
    branches:
      - cd-test
  workflow_call:

jobs:
  echo_run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Running CD..."