name: Test Echo Tuesday

# https://superuser.com/questions/428807/run-a-cron-job-on-the-first-monday-of-every-month // old implementation
on:
  workflow_call:
    inputs:
      retained_branch_count:
        description: "Count of branches to retain"
        type: number
        default: 7

jobs:
  echo_everyday:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input
        run: echo "Retained Branch Count: ${{ inputs.retained_branch_count }}"