name: test trigger on push

on:
  push:
    branches:
      - cd-test
  workflow_call:
    inputs:
      ROLLBACK_REGIONS:
        description:
          Json array of the regions to rollback. For example "['ap-southeast-1',
          'ap-southeast-2']".
        default: "['ap-southeast-1']"
        type: string
  workflow_dispatch:
    inputs:
      ROLLBACK_REGIONS:
        description:
          Json array of the regions to rollback. For example "['ap-southeast-1',
          'ap-southeast-2']".
        default: "['ap-southeast-1']"
        type: string

jobs:
  echo_run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test Input
        run: echo "Rollback regions: ${{ github.event.inputs.ROLLBACK_REGIONS }}"
