name: "Call Simple Workflow"
env:
  BRANCH: "cd-test"

on:
  workflow_dispatch:

jobs:
  trigger_workflow:
    name: "Trigger Autotag Workflow"
    permissions:
      actions: write
    uses: ./.github/workflows/autotag-release.yml
